language: node_js
node_js:
  - "7"
  - "8"
dist: jessie
env:
  - CXX=g++-4.8
script:
  - npm test
  - codecov
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libopencv-dev
notifications:
  slack: hpi:ndJzCSHEaofBnyHTHURo0DFO