FROM siomiz/node-opencv:2.4.x

RUN apt-get clean
RUN apt-get update -y
RUN apt-get install -fyqq ghostscript libgs-dev g++ cmake

EXPOSE 3000 9229

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ADD ./package.json /usr/src/app/
RUN npm install

RUN mkdir -p /tmp/imagecache

ADD ./ /usr/src/app
