version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sh install.sh && npm run production"
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 80:3000
