version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm test
    environment:
      NODE_ENV: development
    ports:
      - 3001:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
